config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :books 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top, :new, :create, :about,]

  before_action :configure_permitted_parameters, if: :devise_controller? 
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    #@user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def show
    @bookn = Book.new
    @book = Book.find(params[:id])
  end
  
  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
  		  <div id="error_explanation">
          <% if @book.errors.any? %>
          <h3>
            <%= @book.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
          <% end %>
        </div>
  		  <div class="form-field">
          <%= form_with model: @book, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Title' %>
              <%= f.text_field :title, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Opinion' %>
              <%= f.text_area :body, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
            </div>
          <% end %>
          <%= link_to "Show", book_path(@book.id)%>
          |
          <%= link_to "Back", books_path%>
        </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice">
  </p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %> errors prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr class="marginb">
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block edit_user_16177' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div class="form-field">
          <%= form_with model: @book, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Title' %>
              <%= f.text_field :title, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Opinion' %>
              <%= f.text_area :body, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: '80x80', fallback: "no_image.jpg"%>
                  <% end %>
                </td>
                <td><%= link_to "#{book.title}", book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>ma

app/views/books/show.html.erb
<main>
  <p id="notice">
  </p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
            </tr>
            <tr class="marginb">
              <th>introduction</th>
              <th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@book.user), class: 'btn btn-outline-secondary btn-block edit_user_16177' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div class="form-field">
          <%= form_with model: @bookn, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Title' %>
              <%= f.text_field :title, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Opinion' %>
              <%= f.text_area :body, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
                  <p>
                    <%= @book.user.name %>
                  </p>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user.id == current_user.id %>
                <td>
                  <%= link_to("Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success edit_book_12089') %>
                </td>
                <td>
                  <%= link_to("Destroy", book_path(@book.id), { method: :delete, data: {confirm: "本当に消しますか？"}, class: 'btn btn-sm btn-danger destroy_book_12089'})%>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome <i class="fas fa-book"></i> <strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
    <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<main>
  <p id="notice">
    
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h2>User info</h2>
  		  <div id="error_explanation">
          <% if @user.errors.any? %>
          <h3>
            <%= @user.errors.count %> errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
          <% end %>
        </div>
  		  <div class="form-field">
          <%= form_with model: @user, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'user_name', 'Name' %>
              <%= f.text_field :name, :class => 'form-control name' %>
            </div>
            <div class="form-group">
              <%= f.label 'user_image', 'Image' %>
              <%= f.attachment_field :profile_image, :class => 'form-control-file user_image' %>
            </div>
            <div class="form-group">
              <%= f.label 'user_introduction', 'Introduction' %>
              <%= f.text_area :introduction, :class => 'form-control introduction' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
            </div>
          <% end %>
        </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr class="marginb">
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block edit_user_16177' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div class="form-field">
          <%= form_with model: @book, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Title' %>
              <%= f.text_field :title, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Opinion' %>
              <%= f.text_area :body, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, size: '80x80', fallback: "no_image.jpg"%>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id)%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice">
  </p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block edit_user_16177' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div class="form-field">
          <%= form_with model: @book, local:true do |f| %>
            <div class="form-group">
              <%= f.label 'book_title', 'Title' %>
              <%= f.text_field :title, :class => 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.label 'book_opinion', 'Opinion' %>
              <%= f.text_area :body, :class => 'form-control book_body' %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: '80x80', fallback: "no_image.jpg"%>
                  <% end %>
                </td>
                <td><%= link_to "#{book.title}", book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>